### ISSUE TITLE
ECKCDSA incorrect hash truncation

### ISSUE THREAD

**Issue by randombit** [randombit/botan#2742]
Current behavior of ECKCDSA does not match ISO 14888-3; hash truncation occurs by taking bits from the left rather than the right. It seems this is due to an error in BSI TR 03111.

Test vectors taken from the ISO spec are included in
https://github.com/ANSSI-FR/libecc/blob/f3abf297e84874278129fb91bc1b89356dd66627/src/tests/ec_self_tests_core.h#L1042

@securitykernel I plan to address this in 3.x by modifying ECKCDSA, which will break compat with 2.x behavior when the hash and group order are not equal in size. LMK if this is an issue / if we need to form some alternate approach.

**Comment by securitykernel** [comment]
Interesting. I remember it was hard to find any test vectors at all. BSI TR 03111 does not mention ECKCDSA anymore specifically, but BSI TR 02102-1 still lists it as a recommended algorithm. I will check older versions of TR 031111 on Monday and if there is an error, check back with BSI. Do you have a recent version of ISO 14888-3 at hand?

**Comment by randombit** [comment]
> Do you have a recent version of ISO 14888-3 at hand?

I do not. This was reported to me by @rb-anssi who indicated that the tests in libecc were taken directly from the ISO doc.

The spec referenced in our test vectors (http://www.tta.or.kr/include/Download.jsp?filename=stnfile/TTAK.KO-12.0015_R2.pdf) does seem to include some tests where the curve order and hash do not match, but only for GF(2^m) curves. However this indicates the spec must somewhere specify how truncation occurs. I'll try feeding pieces into Google translate to see if I can figure that out. [Of course this Korean spec may not match the final ISO spec in any case, standards being what they are]

**Comment by rb-anssi** [comment]
Hi,

Thanks @randombit for the references, and your link on the Korean standard rang a bell!

After some digging, it seems that there is actually a **third revision R3** of this Korean standard (http://www.tta.or.kr/include/Download.jsp?filename=stnfile/TTAK.KO-12.0015_R3.pdf) where the test vector from ISO14888-3 can be found in appendix II.2 (secp224r1 with SHA-256). This is actually in line with the 2016 revision of ISO where this hash truncation matter has been revised (or rather made unambiguous) and detailed compared to the previous editions of the standards.

My Korean being as bad as yours, after a "Google translate" operation, the truncation explanation seems to be detailed in the last paragraph of 9.1, and seems (as intelligible as the translation can be) to be in line with the ISO description.

Reards,

**Comment by randombit** [comment]
@securitykernel I'm inclined to guess that there are very few productions users of ECKCDSA - I had always assumed that it was just added to tick the box for BSI TR 02102-1 compliance/completion - and we can safely just change the truncation behavior and relnote it. LMK if you disagree.

Alternately, if BSI does not care about ECKCDSA anymore I would be quite fine with removing in 3.0, but if it is still in 02102 that maybe is not good.

**Comment by securitykernel** [comment]
> @securitykernel I'm inclined to guess that there are very few productions users of ECKCDSA - I had always assumed that it was just added to tick the box for BSI TR 02102-1 compliance/completion - and we can safely just change the truncation behavior and relnote it. LMK if you disagree.

I assume the same. Let me check back with BSI, but it may take a few days to get a response. If you want, go ahead with changing it.

> Alternately, if BSI does not care about ECKCDSA anymore I would be quite fine with removing in 3.0, but if it is still in 02102 that maybe is not good.

I will check back with BSI tomorrow and get back to you ASAP.

**Comment by randombit** [comment]
@securitykernel No rush on my side, during the week right now I am quite occupied. Thank you for following up on this.

**Comment by randombit** [comment]
Unfortunately fixing the truncation problem also pulls in the code in `EMSA1`, which assumes the usual convention. Fixing this would require the `EMSA` impl "knowing" that it was being used in ECKCDSA so it masks rather than shifts. Which adds a lot of complexity to support an algorithm that I am not exactly strongly attached to keeping. :/

I think best resolution here, at least in the near term, is to disable generating new ECKDSA signatures when the hash len is greater than the group order. We continue to allow verification using our incorrect interpretation.

**Comment by randombit** [comment]
A completely alternate `EMSA` implementation, that uses the opposite convention, might also do the trick? Then both conventions could be supported in the same codebase.

**Comment by securitykernel** [comment]
BSI responded that ECKCDSA really is special algorithm and that they don't know anyone using it ATM. And they're fine with just break compatibility with a fix here and add a corresponding changelog entry.

**Comment by securitykernel** [comment]
Can we merge this for 3.0? #2749 is still open probably because my feedback came after the PR was created.

**Comment by lieser** [comment]
Maybe this is already fixed with https://github.com/randombit/botan/commit/c772d2748299c18359b2b401300d58e00b6fa010, so https://github.com/randombit/botan/pull/2749 would no longer be needed?

@randombit A little off topic, but could you elaborate what you mean in that commit with `not an even multiple
of 8 bits`?
Don't see how an odd multiple of 8 bits could have cause a problem before.

**Comment by randombit** [comment]
@lieser Sorry, coming back to this issue. I just meant where `bits % 8 != 0` and used sloppy terminology.

I don't think #2751 is a resolution to this issue. I believe that was to fix a second (somewhat related) problem where ECKCDSA was incorrect when for example the group order was not a multiple of 8 bits (namely P-521). I see we are still not testing using the case where the digest is longer than the group order (those tests can be found for instance https://github.com/ANSSI-FR/libecc/blob/master/src/tests/ec_self_tests_core.h#L1264) and I think that is the problem described in this ticket.
